name: native_image_picker_macos_example
description: "Demonstrates usage of the native_image_picker_macos plugin."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  native_image_picker_macos:
    path: ../
  image_picker_macos: ^0.2.1+1
  image_picker: ^1.1.0
  video_player: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  mockito: ^5.4.5
  build_runner: ^2.4.14
  image_picker_platform_interface: ^2.10.1
  plugin_platform_interface: ^2.1.8

flutter:
  uses-material-design: true
