ci:
  - changed-files:
    - any-glob-to-all-files:
      - .github/**

documentation:
  - changed-files:
    - any-glob-to-all-files:
      - CONTRIBUTING.md
      - CHANGELOG.md
      - README.md

example:
  - changed-files:
      - any-glob-to-all-files: example/**

test:
  - changed-files:
      - any-glob-to-all-files:
          - test/**
          - example/integration_test/**
          - example/macos/RunnerTests/**
          - example/macos/RunnerUITests/**
          - example/test/**

dart:
  - changed-files:
      - any-glob-to-all-files:
          - lib/**/*.dart
          - test/**/*.dart
          - example/**/*.dart

swift:
  - changed-files:
      - any-glob-to-all-files:
          - macos/**/*.swift
          - example/macos/**/*.swift
